/* Generated By:JavaCC: Do not edit this line. JavaToDartTranspilerConstants.java */
package java_to_dart_transpiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaToDartTranspilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IFSYMBOL = 5;
  /** RegularExpression Id. */
  int ELSESYMBOL = 6;
  /** RegularExpression Id. */
  int FORSYMBOL = 7;
  /** RegularExpression Id. */
  int WHILESYMBOL = 8;
  /** RegularExpression Id. */
  int RETURNSYMBOL = 9;
  /** RegularExpression Id. */
  int VOIDSYMBOL = 10;
  /** RegularExpression Id. */
  int INTSYMBOL = 11;
  /** RegularExpression Id. */
  int STRINGSYMBOL = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int MULTIPLY = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int MODULO = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int NOT_EQUALS = 24;
  /** RegularExpression Id. */
  int LESS_THAN = 25;
  /** RegularExpression Id. */
  int LESS_THAN_EQUALS = 26;
  /** RegularExpression Id. */
  int GREATER_THAN = 27;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUALS = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int LEFT_BRACE = 31;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 35;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 38;
  /** RegularExpression Id. */
  int STRING_LITERAL = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"return\"",
    "\"void\"",
    "\"int\"",
    "\"String\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
  };

}
